spring:
  datasource:
    url: jdbc:h2:file:~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2

